services:
  api:
    build: ./backend
    container_name: toolbox-api
    restart: unless-stopped
    volumes:
      - ./data:/srv/data
      - ./models:/srv/models
    environment:
      - TZ=America/Costa_Rica

  web:
    build: ./frontend
    container_name: toolbox-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3090:80"
